### ISSUE TITLE
Feature request: add interpolation variable for commit hash

### ISSUE THREAD

**Issue by pe8ter** [mrozekma/git-web-link#1]
When generating links to a Git web host, the only real refinement you can make to the file version is to choose the branch name. The issue with this is that, except for a few select branches, most branches are ephemeral and will not exist beyond some relatively near-term point in time.

It would be helpful to add the current commit hash as an interpolation variable option when constructing the web URL. Something like `${commit}`. Then we could have links like this:

`https://github.com/mrozekma/git-web-link/blob/ecf0e5df2ef4d32858ae22e5ca425ec1c665145e/src/extension.ts#L15`

The reason why this is helpful is that I do a lot of code deep dives and then write up my findings. If the code in a branch changes constantly, then the links in my document will be invalid fairly quickly. If I could generate a link to a commit instead, my links would stay valid forever.

What do you think?

**Comment by mrozekma** [comment]
Good idea. I normally make links that I'm sending to someone to follow immediately, so I've never thought of that before. Should be live soon in version 1.2.0
